### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by anroba** [HeRAMS-WHO/ls-responsepicker#1]
According to the name, this plugin allows to copy previous answers.
It is correct?

I installed the plugin but I can not see new features.
After enabling for a survey "Config -> plugings -> Use this survey response picker" nothing happens.
Where I can pickup old answers?

**Comment by SamMousa** [comment]
1. Enable tokens.
2. Set a token to have multiple uses (for example usesleft = 100)
3. Click the token link.

It should show you a response selection screen if there is an existing response.
